# Spring boot application
spring:
  application:
    name: myshop-service-redis-provider
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    host: 192.168.132.128
    database: 0
    port: 6379
    password:
    #sentinel:
      #master: mymaster
      #nodes: 192.168.132.128:26379, 192.168.132.128:26380, 192.168.132.128:26381
server:
  port: 8503

# Services Versions
services:
  versions:
    redis:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  ## Base packages to scan Dubbo Component：@com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.zhouboxi.myshop.service.redis.provider.api.impl
  ## ApplicationConfig Bean
  application:
    id: myshop-service-redis-provider
    name: myshop-service-redis-provider
    qos-port: 22224
    qos-enable: true
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20883
    status: server
    serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://192.168.132.128:2181?backup=192.168.132.128:2182,192.168.132.128:2183

# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool